### PR TITLE
added button popup source code

### PR DESCRIPTION
**Pull request by stevetangue**
* update/clean up html and css
* added button pop up source code

### CODE REVIEW

**Comment by prithaupadhyay** [comment]
@stevetangue Please provide a screenshot of the final pop up.

**Comment by prithaupadhyay** [comment]
@stevetangue Kindly resolve the conflicts.

**Comment by stevetangue** [comment]
Will do soon thanks

**Comment by stevetangue** [comment]
Please find attached screenshots - enhanced overall look and feel 
- give you some examples ideas where you may decide to keep or update as you please ...
Cheers

image

image

**Comment by prithaupadhyay** [comment]
@stevetangue I really liked the style of source code button in the 1st row and  3rd column. You can keep it as the final button design.

**Comment by prithaupadhyay** [comment]
@stevetangue  Kindly resolve the conflicts.

**Comment by stevetangue** [comment]
@prithaupadhyay done - cheers

**Pull request merged**
